### ISSUE TITLE
ImportError: No module named cryptography.hazmat.backends

### ISSUE THREAD

**Issue by kdeloach** [azavea/ansible-terraform#3]
I installed molecule to run the unit tests but got this error. Which version of molecule should be used?

```
> molecule test
Traceback (most recent call last):
  File "/var/projects/ansible-terraform/env/bin/molecule", line 7, in <module>
    from molecule.cli import main
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/cli.py", line 45, in <module>
    from molecule import commands
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/commands/__init__.py", line 25, in <module>
    from molecule.commands import base  # noqa
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/commands/base.py", line 24, in <module>
    from molecule import core
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/core.py", line 32, in <module>
    from molecule import config
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/config.py", line 27, in <module>
    from molecule import utilities
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/utilities.py", line 31, in <module>
    import paramiko
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 32, in <module>
    from cryptography.hazmat.backends import default_backend
ImportError: No module named cryptography.hazmat.backends
```

**Comment by maurizi** [comment]
I recently encountered this on a different project https://github.com/OpenTreeMap/otm-mobile-skins/pull/79

The fix was to ensure that `libssl-dev` and `libffi-dev` are installed on the system before installing anything that transitively depends on `cryptography`, like `paramiko`

**Comment by kdeloach** [comment]
Thanks, I was missing `libssl-dev`!

I tried molecule version 1.8.4-1.8.0 and each one failed with this error:

```
> molecule test
Traceback (most recent call last):
  File "/var/projects/ansible-terraform/env/bin/molecule", line 7, in <module>
    from molecule.cli import main
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/cli.py", line 47, in <module>
    import molecule.commands
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/commands.py", line 36, in <module>
    from molecule import core
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/core.py", line 37, in <module>
    from molecule.provisioners import openstackprovisioner
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/molecule/provisioners/openstackprovisioner.py", line 23, in <module>
    import shade
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/shade/__init__.py", line 19, in <module>
    import os_client_config
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/os_client_config/__init__.py", line 19, in <module>
    from os_client_config import cloud_config
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 18, in <module>
    from keystoneauth1 import adapter
  File "/var/projects/ansible-terraform/env/local/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 15, in <module>
    from positional import positional
ImportError: No module named positional

```

Version 1.7.0 worked but the tests failed.

**Comment by hectcastro** [comment]
How did you install Molecule?

**Comment by kdeloach** [comment]
`pip install molecule`

**Comment by hectcastro** [comment]
I might try reinstalling it. Looking at the traceback, it seems like a dependency of a dependency to Molecule is missing.

**Comment by kdeloach** [comment]
Fixed by doing:

```
pip install pytz
git clone git@github.com:morganfainberg/positional.git
cd positional
python setup.py build
python setup.py install
pip install molecule
```
